selected_scheme scheme-infraonly
TEXDIR /data/data/com.termux/files/usr/share/texlive/2026
TEXMFCONFIG ~/.texlive2026/texmf-config
TEXMFHOME ~/texmf
TEXMFLOCAL /data/data/com.termux/files/usr/share/texlive/texmf-local
TEXMFSYSCONFIG /data/data/com.termux/files/usr/share/texlive/2026/texmf-config
TEXMFSYSVAR /data/data/com.termux/files/usr/share/texlive/2026/texmf-var
TEXMFVAR ~/.texlive2026/texmf-var
instopt_adjustpath 1
instopt_adjustrepo 1
instopt_letter 0
instopt_portable 0
instopt_write18_restricted 1
tlpdbopt_autobackup 0
tlpdbopt_create_formats 1
tlpdbopt_desktop_integration 0
tlpdbopt_file_assocs 0
tlpdbopt_generate_updmap 0
tlpdbopt_install_docfiles 0
tlpdbopt_install_srcfiles 0
tlpdbopt_post_code 1
tlpdbopt_sys_bin /data/data/com.termux/files/usr/bin
tlpdbopt_sys_info /data/data/com.termux/files/usr/share/info
tlpdbopt_sys_man /data/data/com.termux/files/usr/share/man
tlpdbopt_w32_multi_user 1
